version: "3.0"
services:
  express:
    #path to dockerfile
    build: .
    ports:
      - "4000:4000"
    # username/image-name
    image: qx4mx/vidsync
    #make sure .env file is created in root or use envoirment: - MONGO_URI = xxx ytApi = xxx instead
    env_file:
      - .env
    links:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"