{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "vidchart.serviceAccountName" . }}
  labels:
{{ include "vidchart.labels" . | indent 4 }}
{{- end -}}
